### PR TITLE
 Add command-line flags to set proxy for importers

### PR DESCRIPTION
**Pull request by aauss**
In the case of working behind a firewall, the current importers throw "ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it". If it is also not possible to create a global proxy, setting a proxy for the importers becomes necessary.

### CODE REVIEW

**Comment by nathanathan** [comment]
I would rather just use the HTTP_PROXY environment variables so there is less code for passing command line flags around. In a linux shell I'm able to run commands scripts with environment variables defined like this:
`HTTP_PROXY=http://exmaple.com python -m epitator.importers.import_geonames`
Would that approach work for you? If so, we could suggest it in the error message.

**Comment by aauss** [comment]
Unfortunately, setting the proxy via the environment variable through the shell (Windows) does not work for me. I am not very familiar with networking, but I assume that the environment variable is only valid for the importer script. However, the method urlopen() triggers several modules which will again have the default environment setting without the proxy settings (only an assumption).

I think it is a good idea to have the command-line flag because most institutions that want to work with epidemiological data, such as hospitals and public health institutes, are behind firewalls and run Windows (at least here in Germany/Europe). Therefore, I would be happy if more people could use EpiTator without obstacles.

Here is my error message after setting the proxy through the environment variable which is not an connection refused error as when just running the import without the setting of proxies:

Dropping previous data...
Traceback (most recent call last):
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\site-packages\epitator\importers\import_wikidata.py", line 78, in <module>
    import_wikidata(args.drop_previous)
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\site-packages\epitator\importers\import_wikidata.py", line 41, in import_wikidata
    """
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\******\AppData\Local\Continuum\anaconda3\envs\epi_con\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

Thank you for your time and consderation!

**Comment by nathanathan** [comment]
It looks like the syntax for windows environment variables is a little different:
```
set HTTP_PROXY=http://example.com
python -m epitator.importers.import_geonames
```
You might need to quote or escape the url differently when passing it it that way. Adding print(os.environ["HTTP_PROXY"]) to the python script should show whether the correct value is being passed in. Environment variables should be passed through to all modules and child processes.

If it is necessary to use command line flags, I think the amount of code could still be reduced by setting os.environ["HTTP_PROXY"] right after the args are parsed instead of passing variables to the importer functions.

**Comment by aauss** [comment]
Okay, I printed the proxy settings within Python, and that helped me figure out the problem. I guess my pull request is superfluous since setting the environment variable in the shell should be enough. I am sorry if I bothered you with the PR. 

If you want to keep the print message with the hint to set the proxy or even keep the flag (in your suggested smaller form), I can do another PR.

Thank you for your time!

**Comment by nathanathan** [comment]
I like the proxy hint message. It will help people behind firewalls like yours. I don't want to add unnecessary CLI flags though.
Thanks!

**Comment by aauss** [comment]
I adopted your suggestion and only give hints in case of URLErrors.

**Comment by nathanathan** [comment]
Thanks!

**Pull request merged**
