### PR TITLE
Add resolved species annotation

### PR DESCRIPTION
**Pull request by nathanathan**
This adds a ITIS data import script `python -m epitator.importers.import_species` that makes it possible for the resolved keyword annotator to annotate species names. This includes some refactoring that makes breaking changes to the embedded sqlite database and resolved keyword annotator.

### CODE REVIEW

**Comment by nathanathan** [comment]
@Broham The command should be `python -m epitator.importers.import_all`. I need to update that error message.

**Comment by Broham** [comment]
@nathanathan - i've been getting inconsistent behavior that ends in an error when trying to import the missing databases.  Below are two example runs that ended in errors:

```~/Documents/development/EpiTator on  species-resolution! ⌚ 14:05:48
$ python -m epitator.importers.import_all --drop-previous
Dropping previous data...
Loading disease ontology...
Importing entities from disease ontology...
Importing synonyms from disease ontology...
Removing previous ITIS data...
Downloading ITIS data from: https://www.itis.gov/downloads/itisSqlite.zip
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/abemiessler/Documents/development/EpiTator/epitator/importers/import_all.py", line 21, in <module>
    import_species(args.drop_previous)
  File "epitator/importers/import_species.py", line 52, in import_species
    itis_db, itis_version = download_itis_database()
  File "epitator/importers/import_species.py", line 24, in download_itis_database
    zipfile = ZipFile(StringIO(url.read()))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

~/Documents/development/EpiTator on  species-resolution! ⌚ 14:08:02
$ python -m epitator.importers.import_all --drop-previous
Dropping previous data...
Loading disease ontology...
Importing entities from disease ontology...
Importing synonyms from disease ontology...
Removing previous ITIS data...
Downloading ITIS data from: https://www.itis.gov/downloads/itisSqlite.zip
Download complete
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/abemiessler/Documents/development/EpiTator/epitator/importers/import_all.py", line 21, in <module>
    import_species(args.drop_previous)
  File "epitator/importers/import_species.py", line 60, in import_species
    """)
sqlite3.OperationalError: disk I/O error```

**Comment by Broham** [comment]
More often than not the file downloads successfully and I end up getting the `disk I/O error` message.

**Comment by nathanathan** [comment]
@Broham The Zipfile error is probably caused by connection or server issues that corrupt the file during the download. There isn't much we can do about that. I've changed the way the temporary db file is managed to try to address some potential causes for the second issue. I didn't encounter it so it is probably system specific. What version of python are you using? I'm going to merge this so I can move forward with the deployment work these changes require, but I plan to continue tracking down the import script bug you found.

**Comment by Broham** [comment]
@nathanathan - i'm running 2.7

**Pull request merged**
